export const LOADING = 'LOADING';
export const BASKETS_LOADED = 'BASKETS_LOADED';
export const LOADING_MATERIALS = 'LOADING_MATERIALS';
export const MATERIALS_LOADED = 'MATERIALS_LOADED';
export const CLUSTER_MATERIALS_LOADED = 'CLUSTER_MATERIALS_LOADED';
export const LOADING_CLUSTER_MATERIALS = 'LOADING_CLUSTER_MATERIALS';
export const SEARCH_BASKET_CHANGED = 'SEARCH_BASKET_CHANGED';
export const CLOSE_LOADED_CLUSTER = 'CLOSE_LOADED_CLUSTER';
export const CLOSE_LOADED_BASKET = 'CLOSE_LOADED_BASKET';
export const SET_BASKET_TYPE = 'SET_BASKET_TYPE';
export const CLEARSEARCH = 'CLEARSEARCH';
export const ONMATERIALDRAG = 'ONMATERIALDRAG';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH= 'SET_AUTH_REDIRECT_PATH';

export const GET_FILTER_VALUES = 'GET_FILTER_VALUES';
export const HANDLE_FILTER_ERRORS = 'HANDLE_FILTER_ERRORS';

export const GET_DIVISION_ATTRIBUTES = 'GET_DIVISION_ATTRIBUTES';
export const SET_DIVISION_ATTRIBUTES = 'SET_DIVISION_ATTRIBUTES';
